apiVersion: v1
clusters:
- cluster:
    certificate-authority: /var/lib/minikube/certs/ca.crt  # Update this path if needed
    server: https://192.168.49.2:8443  # Update with your local Kubernetes API server URL
  name: minikube  # Name of your cluster
contexts:
- context:
    cluster: minikube
    user: minikube  # Update with your user name if different
  name: minikube  # Name of your context
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube  # Update with your user name if different
  user:
    token: ${{ secrets.KUBE_CONFIG_TOKEN }}  # Replace with your token