name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG_TOKEN }}" > kubeconfig.yaml
          kubectl config set-credentials minikube --token="${{ secrets.KUBE_CONFIG_TOKEN }}"
          kubectl config set-context minikube --cluster=minikube --user=minikube
          kubectl config use-context minikube
        env:
          KUBE_CONFIG_TOKEN: ${{ secrets.KUBE_CONFIG_TOKEN }}

      - name: Deploy to Kubernetes
        run: |
          kubectl --kubeconfig=kubeconfig.yaml apply -f path/to/your/kubernetes/manifests/
