name: Deploy to Minikube

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker and kubectl
        run: |
          # Assuming Minikube is already running on your self-hosted runner
          # Ensure Minikube is started with appropriate driver and settings
          minikube start --driver=docker

          # Set kubectl context to Minikube
          kubectl config use-context minikube

      - name: Deploy using Skaffold
        run: |
          skaffold dev
