name: Deploy to Minikube

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: false

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          docker build -t noura5/auth1 ./auth
          docker push noura5/auth1
          docker build -t noura5/ticketing-client1 ./client
          docker push noura5/ticketing-client1
          docker build -t noura5/orders1 ./orders
          docker push noura5/orders1
          docker build -t noura5/payments1 ./payments
          docker push noura5/payments1
          docker build -t noura5/tickets1 ./tickets
          docker push noura5/tickets1

      - name: Set up Minikube Docker Environment
        run: eval $(minikube -p minikube docker-env)

      - name: Set up kubectl and Skaffold
        env:
          KUBE_CONFIG_TOKEN: ${{ secrets.KUBE_CONFIG_TOKEN }}
        run: |
          echo "${{ secrets.KUBE_CONFIG_TOKEN }}" > kubeconfig.yaml
          kubectl config set-credentials minikube --token="${{ secrets.KUBE_CONFIG_TOKEN }}"
          kubectl config set-context minikube --cluster=minikube --user=minikube
          kubectl config use-context minikube
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x skaffold
          mv skaffold /usr/local/bin

      - name: Deploy using Skaffold
        run: skaffold dev -v=debug
