name: Deploy to Minikube

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker and kubectl
        run: |
          minikube start --driver=docker

          kubectl config use-context minikube

          df -h

      - name: Deploy using Skaffold
        run: |
          skaffold dev
